/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChargePanel.java
 *
 * Created on Oct 30, 2010, 9:20:55 AM
 */

package adagent;

/**
 *
 * @author Kawai
 */
public class ChargePanel extends java.awt.Panel {

    /** Creates new form ChargePanel */
    public ChargePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adagent.ADagentApp.class).getContext().getResourceMap(ChargePanel.class);
        tContTypeQuery = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery(resourceMap.getString("tContTypeQuery.query")); // NOI18N
        tContTypeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(((javax.persistence.Query)null).getResultList());
        tPageTypeQuery = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery(resourceMap.getString("tPageTypeQuery.query")); // NOI18N
        tPageTypeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(((javax.persistence.Query)null).getResultList());
        tSizeTypeQuery = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery(resourceMap.getString("tSizeTypeQuery.query")); // NOI18N
        tSizeTypeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(((javax.persistence.Query)null).getResultList());
        jScrollPane2 = new javax.swing.JScrollPane();
        ContentCostTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        PageCostTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        SizeWeightTable = new javax.swing.JTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        ContentCostTable.setName("ContentCostTable"); // NOI18N
        jScrollPane2.setViewportView(ContentCostTable);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        PageCostTable.setName("PageCostTable"); // NOI18N
        jScrollPane3.setViewportView(PageCostTable);

        add(jScrollPane3, java.awt.BorderLayout.NORTH);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        SizeWeightTable.setName("SizeWeightTable"); // NOI18N
        jScrollPane4.setViewportView(SizeWeightTable);

        add(jScrollPane4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContentCostTable;
    private javax.swing.JTable PageCostTable;
    private javax.swing.JTable SizeWeightTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.util.List<adagent.TContType> tContTypeList;
    private javax.persistence.Query tContTypeQuery;
    private java.util.List<adagent.TPageType> tPageTypeList;
    private javax.persistence.Query tPageTypeQuery;
    private java.util.List<adagent.TSizeType> tSizeTypeList;
    private javax.persistence.Query tSizeTypeQuery;
    // End of variables declaration//GEN-END:variables

}
