/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerPanel.java
 *
 * Created on Oct 30, 2010, 9:16:01 AM
 */

package adagent;

/**
 *
 * @author Kawai
 */
public class CustomerPanel extends java.awt.Panel {


    public CustomerPanel (Integer oID) {
        initComponents();
        query = em.createNamedQuery("TEmployee.findByEID");
        query.setParameter("eID", (Integer)oID);
        employee = (TEmployee)query.getSingleResult();
        for(TOrder order : employee.getTOrderList())
        {
            
        }
    }

    /** Creates new form CustomerPanel */
    public CustomerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ADagentPU").createEntityManager();
        tOrderList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ((javax.persistence.Query)null).getResultList();
        query1 = java.beans.Beans.isDesignTime() ? null : em.createQuery("");
        displayEmployee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        contTypeTableCellRenderer1 = new adagent.ContTypeTableCellRenderer();
        pageTypeTableCellRenderer1 = new adagent.PageTypeTableCellRenderer();
        sizeTypeTableCellRenderer1 = new adagent.SizeTypeTableCellRenderer();
        editCustomerButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adagent.ADagentApp.class).getContext().getResourceMap(CustomerPanel.class);
        displayEmployee.setFont(resourceMap.getFont("displayEmployee.font")); // NOI18N
        displayEmployee.setText(resourceMap.getString("displayEmployee.text")); // NOI18N
        displayEmployee.setName("displayEmployee"); // NOI18N
        add(displayEmployee, java.awt.BorderLayout.CENTER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        orderTable.setBackground(resourceMap.getColor("orderTable.background")); // NOI18N
        orderTable.setName("orderTable"); // NOI18N
        orderTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                orderTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        add(jScrollPane1, java.awt.BorderLayout.NORTH);

        contTypeTableCellRenderer1.setName("contTypeTableCellRenderer1"); // NOI18N
        add(contTypeTableCellRenderer1, java.awt.BorderLayout.SOUTH);

        pageTypeTableCellRenderer1.setName("pageTypeTableCellRenderer1"); // NOI18N
        add(pageTypeTableCellRenderer1, java.awt.BorderLayout.EAST);

        sizeTypeTableCellRenderer1.setName("sizeTypeTableCellRenderer1"); // NOI18N
        add(sizeTypeTableCellRenderer1, java.awt.BorderLayout.WEST);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(adagent.ADagentApp.class).getContext().getActionMap(CustomerPanel.class, this);
        editCustomerButton.setAction(actionMap.get("editCustomerRecord")); // NOI18N
        editCustomerButton.setName("editCustomerButton"); // NOI18N
        add(editCustomerButton, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void orderTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_orderTablePropertyChange
        System.out.println("proertyChange");
        // TODO add your handling code here:
}//GEN-LAST:event_orderTablePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private adagent.ContTypeTableCellRenderer contTypeTableCellRenderer1;
    private javax.swing.JLabel displayEmployee;
    private javax.swing.JButton editCustomerButton;
    private javax.persistence.EntityManager em;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private adagent.PageTypeTableCellRenderer pageTypeTableCellRenderer1;
    private javax.persistence.Query query1;
    private adagent.SizeTypeTableCellRenderer sizeTypeTableCellRenderer1;
    private java.util.List tOrderList;
    // End of variables declaration//GEN-END:variables

    private adagent.TEmployee employee;
    private javax.persistence.Query query;
}
