/*
 * BadmintonClient.java
 *
 * These program Create and use a client class to access the server instance.
 *
 * Copyright (c) 2007 Aptech Software Limited. All Rights Reserved.
 */

package Client;

import java.awt.Color;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Scores.*;

/**
 *
 * @author  Vincent
 */
public class BadmintonClient extends javax.swing.JFrame {
    
    /** Creates new form BadmintonClient */
    public BadmintonClient() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        }
        
        getContentPane().setBackground(new Color(212,208,200));
        initComponents();
        try {            
            stub = (RmiSampleInterface) Naming.lookup("rmi://localhost:1099/BadmintonServer");
            Scores score = stub.getScore();
            updateScores(score);
            System.out.println("Player 1 " + score.getStrPlayer(1));
            System.out.println("Player 2 " + score.getStrPlayer(2));
        } catch (RemoteException ex) {
            ex.printStackTrace();
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        } catch (NotBoundException ex) {
            ex.printStackTrace();
        }
        
    }
    public void updateScores(Scores score) {
        txtPlayer1.setText(score.getStrPlayer(1));
        txtPlayer2.setText(score.getStrPlayer(2));
        
        txtPlayer1Set1.setText(String.valueOf(score.getPlayerSet(1,1)));
        txtPlayer2Set1.setText(String.valueOf(score.getPlayerSet(2,1)));
        
        txtPlayer1Set2.setText(String.valueOf(score.getPlayerSet(1,2)));
        txtPlayer2Set2.setText(String.valueOf(score.getPlayerSet(2,2)));
        
        txtPlayer1Set3.setText(String.valueOf(score.getPlayerSet(1,3)));
        txtPlayer2Set3.setText(String.valueOf(score.getPlayerSet(2,3)));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblHeader = new javax.swing.JLabel();
        pnlPlayer = new javax.swing.JPanel();
        lblPlayer1 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        lblPlayer2 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JTextField();
        pnlSets = new javax.swing.JPanel();
        txtPlayer1Set1 = new javax.swing.JTextField();
        txtPlayer1Set2 = new javax.swing.JTextField();
        txtPlayer1Set3 = new javax.swing.JTextField();
        txtPlayer2Set1 = new javax.swing.JTextField();
        txtPlayer2Set2 = new javax.swing.JTextField();
        txtPlayer2Set3 = new javax.swing.JTextField();
        btnUpdateScore = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Score Board");
        setResizable(false);
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Badminton Score Board");
        lblHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHeader.setPreferredSize(new java.awt.Dimension(520, 40));
        getContentPane().add(lblHeader);

        pnlPlayer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        pnlPlayer.setEnabled(false);
        pnlPlayer.setPreferredSize(new java.awt.Dimension(240, 100));
        lblPlayer1.setText("Player  1");
        lblPlayer1.setPreferredSize(new java.awt.Dimension(70, 20));
        pnlPlayer.add(lblPlayer1);

        txtPlayer1.setEditable(false);
        txtPlayer1.setPreferredSize(new java.awt.Dimension(140, 20));
        pnlPlayer.add(txtPlayer1);

        lblPlayer2.setText("Player  2");
        lblPlayer2.setPreferredSize(new java.awt.Dimension(70, 20));
        pnlPlayer.add(lblPlayer2);

        txtPlayer2.setEditable(false);
        txtPlayer2.setPreferredSize(new java.awt.Dimension(140, 20));
        pnlPlayer.add(txtPlayer2);

        getContentPane().add(pnlPlayer);

        pnlSets.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 10));

        pnlSets.setBorder(javax.swing.BorderFactory.createTitledBorder("Sets"));
        pnlSets.setPreferredSize(new java.awt.Dimension(270, 100));
        txtPlayer1Set1.setEditable(false);
        txtPlayer1Set1.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer1Set1);

        txtPlayer1Set2.setEditable(false);
        txtPlayer1Set2.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer1Set2);

        txtPlayer1Set3.setEditable(false);
        txtPlayer1Set3.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer1Set3);

        txtPlayer2Set1.setEditable(false);
        txtPlayer2Set1.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer2Set1);

        txtPlayer2Set2.setEditable(false);
        txtPlayer2Set2.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer2Set2);

        txtPlayer2Set3.setEditable(false);
        txtPlayer2Set3.setPreferredSize(new java.awt.Dimension(40, 20));
        pnlSets.add(txtPlayer2Set3);

        getContentPane().add(pnlSets);

        btnUpdateScore.setText("Update Score");
        btnUpdateScore.setPreferredSize(new java.awt.Dimension(100, 23));
        btnUpdateScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateScoreActionPerformed(evt);
            }
        });

        getContentPane().add(btnUpdateScore);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-539)/2, (screenSize.height-215)/2, 539, 215);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnUpdateScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateScoreActionPerformed
     
// TODO add your handling code here:  
         try {
            Scores score = stub.getScore();
            updateScores(score);
         	System.out.println("Player1:" + stub.getPlayer(1) + ",Player2:" + stub.getPlayer(2));
        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
       
    }//GEN-LAST:event_btnUpdateScoreActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BadmintonClient().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateScore;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JPanel pnlPlayer;
    private javax.swing.JPanel pnlSets;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer1Set1;
    private javax.swing.JTextField txtPlayer1Set2;
    private javax.swing.JTextField txtPlayer1Set3;
    private javax.swing.JTextField txtPlayer2;
    private javax.swing.JTextField txtPlayer2Set1;
    private javax.swing.JTextField txtPlayer2Set2;
    private javax.swing.JTextField txtPlayer2Set3;
    // End of variables declaration//GEN-END:variables
    RmiSampleInterface stub;
}
