<%@ Page Language="C#" MasterPageFile="~/TRC.Master" AutoEventWireup="true" CodeBehind="City.aspx.cs" Inherits="WebApplication.City" Title="CityList" %>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder" runat="server">
 <form id="theForm" runat="server">
    <div id="table">
    <asp:GridView ID="gvCityResults" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ShowFooter="True" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="cID" DataSourceID="SqlDataSourceCity">
        <Columns>
            <asp:TemplateField HeaderText="cID" InsertVisible="False" SortExpression="cID">
                <EditItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("cID") %>'></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("cID") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                <asp:Button Text="Add" CommandName="Insert" OnCommand="gvCityResults_AddNew" CausesValidation="true" runat="server" ID="btInsert"/>&nbsp;
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="cName" SortExpression="cName">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("cName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("cName") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                <asp:TextBox ID="cNameBox" runat="server" Text="" ></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="cZone" SortExpression="cZone">
                <EditItemTemplate>
                        <asp:DropDownList ID="DropDownZone" runat="server" AutoPostBack="False" SelectedValue='<%# Bind("cZone") %>'>
                        <asp:ListItem Selected="True" Value="1">1</asp:ListItem>
                        <asp:ListItem Value="2">2</asp:ListItem>
                        </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("cZone") %>'></asp:Label>
                </ItemTemplate>
                 <FooterTemplate>
        <asp:DropDownList ID="ZoneList" runat="server" AutoPostBack="False" SelectedValue='<%# Bind("cZone") %>'>
        <asp:ListItem Selected="True" Value="1">1</asp:ListItem>
        <asp:ListItem Value="2">2</asp:ListItem>
        </asp:DropDownList>
                 </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSourceCity" runat="server" ConnectionString="<%$ ConnectionStrings:SRCConnection %>"
            SelectCommand="SELECT [cID], [cName], [cZone] FROM [tCity]" UpdateCommand="UPDATE tCity SET cName = @cName, cZone = @cZone WHERE (cID = @cID)" InsertCommand="INSERT INTO tCity(cName, cZone) VALUES (@cName, @cZone)">
            <UpdateParameters>
                <asp:Parameter Name="cName" Type="String"/>
                <asp:Parameter Name="cZone" Type="Int32"/>
                <asp:Parameter Name="cID" Type="Int32"/>
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="cName" Type="String"/>
                <asp:Parameter Name="cZone" Type="Int32"/>
            </InsertParameters>
        </asp:SqlDataSource>
    </div>
</form>
</asp:Content>
