/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TablePane.java
 *
 * Created on Nov 4, 2010, 7:55:28 PM
 */

package garment;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kawai
 */
public class TablePane extends java.awt.Panel {

    /** Creates new form TablePane */
    public TablePane(List<Brand> list) {
        initComponents();
        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
        for(int j = 0 ; j < list.size() ; j++){
            Brand brand = list.get(j);
            String [] rowdata = {brand.getSerialNo(),brand.getName(),brand.getPrice()};
            tableModel.addRow(rowdata);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SerialNo", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
