/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'netka' at '10/28/16 11:51 PM' with Gradle 3.0
 *
 * @author netka, @date 10/28/16 11:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
