<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/TRC.master" CodeBehind="Employee.aspx.cs" Inherits="WebApplication.Employee" Title="Employee List"%>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContentPlaceHolder" Runat="server">
 <form id="theForm" runat="server">
    <div id="table">
    <asp:GridView ID="gvEmpResults" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvEmpResults_RowDeleteing" OnRowUpdating="gvEmpResults_RowUpdating" OnRowEditing="gvEmpResults_RowEditing" OnRowCancelingEdit="gvEmpResults_RowCancelingEdit"></asp:GridView>
    </div>
    <div>
        <br />
        <asp:TextBox ID="eNameBox" runat="server" Width="91px"></asp:TextBox>
        <asp:TextBox ID="ePasswordBox" runat="server" Width="94px"></asp:TextBox>
        <asp:TextBox ID="eContactBox" runat="server" Width="75px"></asp:TextBox>
        <asp:Button ID="btnAddNew" runat="server" Text="Add" OnClick="BtnAddNew_Click" />
</div>
</form>
</asp:Content>
